"""Compresses web/index.html and emits it as a C++ array the firmware can serve.

The page is part of the firmware rather than a file on a second partition. That way
`pio run -t upload` ships page and firmware together and their versions cannot drift
apart - which is the failure a filesystem invites: firmware updated, page stale, and
nothing says so.

It is compressed here and served with `Content-Encoding: gzip`, so the ESP32 only
pushes bytes out of flash and the browser does the work.

The generated header goes into the build directory, never into the source tree. A
checked-in generated file rots the moment someone edits the HTML and forgets to
regenerate it; as a build product that cannot happen.
"""

import gzip
import re
import sys
from pathlib import Path

# Called two ways: by PlatformIO as an extra script, where SCons injects Import, and from
# the command line by test/run.sh, which needs the same header to compile the backend on
# the host. One generator either way - a second one would drift from this.
try:
    Import("env")  # noqa: F821
    FROM_PLATFORMIO = True
except NameError:
    FROM_PLATFORMIO = False


HEADER_NAME = "WebPage.h"


def strip_comments(text):
    """Takes the page's comments out on the way into flash, leaving them in the source.

    They are 58% of index.html and 6 KiB of the 10 KiB it compresses to - which is 0.2% of
    the ESP32's flash and worth nothing there, but the page is also the place where the
    reasoning is worth the most, because CSS decisions read as arbitrary without it. So the
    explanation stays where it is read and stops being shipped.

    Only block comments, and that is what makes this safe rather than clever: the page uses
    /* */ throughout, which is this project's style everywhere, so there is no // form to
    remove - and // is exactly what a naive stripper would take out of ws:// and http://.
    The check below is what keeps that assumption from going quiet if it ever stops holding.
    """
    if re.search(r"^\s*//", text, flags=re.M):
        raise SystemExit(
            "embed_web.py: index.html has a // comment. Only /* */ is removed here, because "
            "// cannot be told from the one in ws:// without parsing the page. Use /* */."
        )

    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    # The blank lines the comments leave behind, and the trailing spaces with them.
    text = re.sub(r"[ \t]+$", "", text, flags=re.M)
    return re.sub(r"\n{3,}", "\n\n", text)


def render(compressed):
    lines = [
        "/* Generated by scripts/embed_web.py from web/index.html - do not edit. */",
        "#ifndef _WEB_PAGE_H_",
        "#define _WEB_PAGE_H_",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "/* gzip-compressed, so it is served with Content-Encoding: gzip. */",
        "static const uint8_t WebPageGzip[] = {",
    ]

    for offset in range(0, len(compressed), 16):
        chunk = compressed[offset:offset + 16]
        lines.append("    " + " ".join(f"0x{byte:02x}," for byte in chunk))

    lines += [
        "};",
        "",
        f"static constexpr size_t WebPageGzipSize{{{len(compressed)}u}};",
        "",
        "#endif // _WEB_PAGE_H_",
        "",
    ]
    return "\n".join(lines)


def embed(source, build_dir):
    page = Path(source)

    if not page.is_file():
        raise SystemExit(f"embed_web.py: {page} not found")

    # mtime=0 so the same page always yields the same bytes, which keeps a rebuild from
    # looking like a change.
    source = strip_comments(page.read_text(encoding="utf-8"))
    compressed = gzip.compress(source.encode("utf-8"), compresslevel=9, mtime=0)

    target = Path(build_dir) / HEADER_NAME
    target.parent.mkdir(parents=True, exist_ok=True)
    rendered = render(compressed)

    # Only rewrite when it differs, so an unchanged page does not force a recompile of
    # everything that includes the header.
    if not target.is_file() or target.read_text() != rendered:
        target.write_text(rendered)

    print(f"embed_web.py: {page.name} -> {target} "
          f"({page.stat().st_size} -> {len(source.encode('utf-8'))} without comments "
          f"-> {len(compressed)} bytes)")
    return target.parent


if FROM_PLATFORMIO:
    build_dir = embed(
        Path(env.subst("$PROJECT_DIR")) / "web" / "index.html",  # noqa: F821
        env.subst("$BUILD_DIR"),  # noqa: F821
    )
    env.Append(CPPPATH=[str(build_dir)])  # noqa: F821
elif __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(f"usage: {Path(sys.argv[0]).name} <index.html> <output directory>")

    embed(Path(sys.argv[1]), sys.argv[2])
