"""Compresses web/index.html and emits it as a C++ array the firmware can serve.

The page is part of the firmware rather than a file on a second partition. That way
`pio run -t upload` ships page and firmware together and their versions cannot drift
apart - which is the failure a filesystem invites: firmware updated, page stale, and
nothing says so.

It is compressed here and served with `Content-Encoding: gzip`, so the ESP32 only
pushes bytes out of flash and the browser does the work.

The generated header goes into the build directory, never into the source tree. A
checked-in generated file rots the moment someone edits the HTML and forgets to
regenerate it; as a build product that cannot happen.
"""

import gzip
from pathlib import Path

Import("env")  # noqa: F821


HEADER_NAME = "WebPage.h"


def render(compressed):
    lines = [
        "/* Generated by scripts/embed_web.py from web/index.html - do not edit. */",
        "#ifndef _WEB_PAGE_H_",
        "#define _WEB_PAGE_H_",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "/* gzip-compressed, so it is served with Content-Encoding: gzip. */",
        "static const uint8_t WebPageGzip[] = {",
    ]

    for offset in range(0, len(compressed), 16):
        chunk = compressed[offset:offset + 16]
        lines.append("    " + " ".join(f"0x{byte:02x}," for byte in chunk))

    lines += [
        "};",
        "",
        f"static constexpr size_t WebPageGzipSize{{{len(compressed)}u}};",
        "",
        "#endif // _WEB_PAGE_H_",
        "",
    ]
    return "\n".join(lines)


def embed(source, build_dir):
    page = Path(source)

    if not page.is_file():
        raise SystemExit(f"embed_web.py: {page} not found")

    # mtime=0 so the same page always yields the same bytes, which keeps a rebuild from
    # looking like a change.
    compressed = gzip.compress(page.read_bytes(), compresslevel=9, mtime=0)

    target = Path(build_dir) / HEADER_NAME
    target.parent.mkdir(parents=True, exist_ok=True)
    rendered = render(compressed)

    # Only rewrite when it differs, so an unchanged page does not force a recompile of
    # everything that includes the header.
    if not target.is_file() or target.read_text() != rendered:
        target.write_text(rendered)

    print(f"embed_web.py: {page.name} -> {target} ({page.stat().st_size} -> {len(compressed)} bytes)")
    return target.parent


build_dir = embed(
    Path(env.subst("$PROJECT_DIR")) / "web" / "index.html",  # noqa: F821
    env.subst("$BUILD_DIR"),  # noqa: F821
)

env.Append(CPPPATH=[str(build_dir)])  # noqa: F821
