/******************************************************************************************************************************************************
 *  COPYRIGHT
 *  ---------------------------------------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) Andreas Burnickl                                                                                                 All rights reserved.
 *
 *  \endverbatim
 *  ---------------------------------------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------------------------------------*/
/**     \file       WebFrontend.h
 *      \brief      The half of the web front end that is not a server
 *
 *      \details    What a browser is sent, as opposed to how it is reached: the command
 *                  catalog and the letter grid as JSON, the answer lines and the display
 *                  frames that go out over the socket, and the command a frame carries on
 *                  its way into the parser.
 *
 *                  None of that is a property of a controller, which is why it is here and
 *                  not in a backend. It was in a backend once - written for the ESP32 and
 *                  then copied to the RP2350 - and the copy is what this ends: the catalog
 *                  both pages parse was being generated by two functions that had to be
 *                  kept identical by hand, and a divergence in either would have shown up
 *                  in a browser rather than in a test.
 *
 *                  A backend supplies the other half through WebTransport.h, the way it
 *                  supplies Pixels.h or Storage.h - see platform/avr-dx/README.md for that
 *                  contract. What is left in a backend is what genuinely differs: starting
 *                  a server, registering routes, checking a password, and taking a firmware
 *                  image, which two of them do in two entirely different ways.
 *
******************************************************************************************************************************************************/
#ifndef _WEB_FRONTEND_H_
#define _WEB_FRONTEND_H_

/******************************************************************************************************************************************************
 * I N C L U D E S
******************************************************************************************************************************************************/
#include "StandardTypes.h"

/******************************************************************************************************************************************************
 *  G L O B A L   C O N S T A N T   M A C R O S
******************************************************************************************************************************************************/
/* WebFrontend configuration parameter */
/* Off unless a backend turns it on from its own build, because every target compiles
   firmware/src whole and only two of them have a radio to serve anything over. Off is
   therefore the answer that keeps the AVR-Dx image exactly the size it was. Overridden with
   -DWEB_FRONTEND_SUPPORT=STD_ON, the way DISPLAY_DATA_PIN is overridden, rather than by
   editing here - all four targets share this header. */
#ifndef WEB_FRONTEND_SUPPORT
# define WEB_FRONTEND_SUPPORT                           STD_OFF
#endif

#if (WEB_FRONTEND_SUPPORT == STD_ON)

#include "Pixels.h"
#include "WebTransport.h"

#include <atomic>
#include <stddef.h>

/* The longest command a socket frame may carry. Longer frames are refused rather than
   split, so half a command can never reach the parser. Well above the longest command in
   the reference, whose text overlay is the only one that comes close. */
#define WEB_FRONTEND_MAX_FRAME_LENGTH                   192u

/* In scheduler ticks, so 5 * 10 ms is twenty frames a second. The buffer is 330 bytes, so
   that is under 7 KB/s and only while somebody is watching - sending on every tick would be
   five times that for a display that changes far more slowly. */
#define WEB_FRONTEND_FRAME_INTERVAL_TICKS               5u

/******************************************************************************************************************************************************
 *  C L A S S   W E B   F R O N T E N D
******************************************************************************************************************************************************/
class WebFrontend
{
  public:
    /* One file a clock hands out unchanged: the two pages, the manifest and the two icons.
       Everything a backend needs in order to answer for it, and nothing about how - which is
       why this is a table and not five handlers. It was five handlers, twice, and the ten
       differed only in a blob, a content type and whether a header went out with it.

       The bytes live in the generated WebPage.h, which only WebFrontend.cpp includes: the
       generated arrays have internal linkage, so a second includer would put a second copy
       of both pages in flash. */
    struct AssetType {
        const char* Path;
        const uint8_t* Bytes;
        size_t Size;
        const char* ContentType;
        /* Stored compressed and sent compressed, so the backend has to say so in a header
           and the browser unpacks it. False for the manifest, which is 485 bytes, and for
           the icons, a PNG being deflated already. */
        bool IsGzipped;
    };

/******************************************************************************************************************************************************
 *  P R I V A T E   D A T A   A N D   F U N C T I O N S
******************************************************************************************************************************************************/
  private:
    /* size_t on the left so the multiplication happens there too. Both operands are small
       enough that an int product could not overflow, but the analyser cannot know the
       display's size and is right to ask rather than to work it out. */
    static constexpr size_t FrameSize{static_cast<size_t>(PIXELS_NUMBER_OF_LEDS) * Pixel::getNumberOfColors()};

    /* What was last sent, so an unchanged display costs a comparison rather than a frame.
       Same shape as Persistence, and for the same reason: nothing has to remember to report
       a change, so nothing can forget. Pixels' own dirty flag cannot serve here - render()
       clears it on its way to the strip, and a client that was not due on that tick would
       never learn of the change. */
    byte LastFrame[FrameSize]{};
    byte FrameCountdown{0u};
    /* Set when a client arrives, so the next frame goes out even though nothing changed. A
       browser that connects to a standing display would otherwise wait for the next change -
       on a word clock, up to five minutes of empty panel. Written by whichever context the
       backend's socket callback runs in and cleared by the firmware's tick; a byte either
       way, so a lost race costs one interval. */
    std::atomic<bool> ForceFrame{false};

    WebFrontend() { }
    ~WebFrontend() { }

/******************************************************************************************************************************************************
 *  P U B L I C   F U N C T I O N S
******************************************************************************************************************************************************/
  public:
    static WebFrontend& getInstance() {
        static WebFrontend SingletonInstance;
        return SingletonInstance;
    }

    // methods
    /* What a backend may size a static array of routes with, since the count itself is only
       known in the source. A static_assert there holds the two together, so a file added to
       the table without raising this fails the build rather than one registration. */
    static constexpr byte MaxAssets{5u};

    /* The files a clock serves unchanged, for a backend to register a route per entry and
       answer it from the table. Walked rather than named one by one, so a file added to
       web/ reaches both backends by appearing here. */
    static byte getNumberOfAssets();
    static const AssetType& getAsset(byte Index);

    /* The command catalog as JSON, so a page can build its own form from it, and the panel's
       shape and letters. Both take the body a backend's route handler opened, which is the
       only thing about them that is a backend's business. */
    static void writeCommands(WebResponseBody&);
    static void writeDisplay(WebResponseBody&);

    /* Sends one finished line to whoever is connected. Called from the firmware's task
       through WordclockSerial's line sink, not from a server's. */
    void broadcastLine(const char*);

    /* Sends the pixel buffer as one binary frame, at most every
       WEB_FRONTEND_FRAME_INTERVAL_TICKS and only when it changed. Called from the
       application's tick, after the display has been handed to the strip. */
    void broadcastFrame();

    /* One socket frame's text on its way into the parser, terminator included. Refuses an
       empty frame and one too long to be a command rather than passing either on. */
    static void injectCommand(const char*, size_t);

    /* For a backend's socket callback, which runs outside the firmware's tick. */
    void onClientOpened() { ForceFrame.store(true, std::memory_order_release); }
};

#endif // (WEB_FRONTEND_SUPPORT == STD_ON)

#endif // _WEB_FRONTEND_H_

/******************************************************************************************************************************************************
 *  E N D   O F   F I L E
******************************************************************************************************************************************************/
